### ISSUE TITLE
Multi-target regression

### ISSUE THREAD

**Issue by Albi32** [smarie/python-m5p#12]
Hi!
I really like your work with M5P, I would like to ask if it can be used for multi-target regression. 

Thank you!

**Comment by smarie** [comment]
Hello @Albi32, thanks for the kind words ! 

Unfortunately the current implementation does not support it. In terms of design, the "easiest" way to support multi-target regression would be to create one independent M5P model per target. This is supported in scikit-learn, using the `MultiOutputRegressor` meta-model: https://scikit-learn.org/stable/modules/multiclass.html#multioutputregressor
 
Would this suit your needs?

**Comment by smarie** [comment]
Closing as answered
