### ISSUE TITLE
Can't run examples because lack of .fit() method

### ISSUE THREAD

**Issue by lccatala** [smarie/python-m5p#15]
When running the example, I run into the following error

`Traceback (most recent call last):
  File "/home/luis/Projects/toys/main.py", line 12, in <module>
    reg.fit(X, y)
  File "/home/luis/Projects/toys/.venv/lib/python3.10/site-packages/m5py/main.py", line 214, in fit
    super(M5Base, self).fit(X, y, sample_weight=sample_weight, check_input=check_input)
AttributeError: 'super' object has no attribute 'fit'
`

It seems the class BaseDecisionTree doesn't have a fit() method, however replacing it with _fit() it seems to work. I'm not sure if I should simply replace it or if the class should inherit from something like DecisionTreeRegressor (which would necessitate changing the criterion).

**Comment by smarie** [comment]
Thanks for reporting this @lccatala ! Most probably this is a change due to a newer sklearn version. Could you please find out at which version this `BaseDecisionTree.fit` disappeared ? We'll then be able to implement a legacy-compliant PR to fix this.
Thanks!

**Comment by lccatala** [comment]
Hi @smarie it seems it was in version 1.3
[https://github.com/scikit-learn/scikit-learn/blob/9aaed498795f68e5956ea762fef9c440ca9eb239/sklearn/tree/_classes.py#L176](Version 1.2,2)
[https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d6e0a3e8ddf92a7e5561245224dab102/sklearn/tree/_classes.py#L221](Version 1.3)

I've opened a PR with a quick fix, though I'm not sure if it's the best way of implementing it
