### ISSUE TITLE
`X_idx_sorted` fit argument will not be supported in sklearn>=1.1.0

### ISSUE THREAD

**Issue by tkaraouzene** [smarie/python-m5p#9]
The following line (https://github.com/smarie/python-m5p/blob/main/src/m5py/main.py#L184) will not work with new ``sklearn`` versions since ``X_idx_sorted`` has been deprecated by sklearn (c.f: https://github.com/scikit-learn/scikit-learn/pull/21593)

**Comment by smarie** [comment]
Indeed, good catch @tkaraouzene !
If I'm not mistaken, the line that fails is https://github.com/smarie/python-m5p/blob/main/src/m5py/main.py#L214

Would you like to propose a PR ?

**Comment by smarie** [comment]
Fix available in 0.3.1 released in a few minutes. Thanks @preinaj !
